### ISSUE TITLE
Can't connect to server on cellphone by wifi but 4G is ok

### ISSUE THREAD

**Issue by trngkn** [chrisbeardy/nextcloud-docker-raspberrypi-tutorial#4]
i've installed succesfull a server on my raspbi 3B+, everything is ok but i cant load file or upload file by cellphone with wifi connection but 4G is ok. Plz help me

**Comment by chrisbeardy** [comment]
Hi, as the server works and is accessible from 4G, I would suspect this is an issue with the WiFi / network configuration you are using. I would try using a WiFi network not on the same one as you are using for the pi and see if this works. I would also try a computer on the same WiFi network to see if that works. However as this is not an issue with the setup of the server, which this tutorial is for, I am going to close this issue. I hope you can solve it.
