### ISSUE TITLE
Instructions for k3s nextcloud setup

### ISSUE THREAD

**Issue by magsol** [chrisbeardy/nextcloud-docker-raspberrypi-tutorial#8]
Wondered if you had any intention of porting this tutorial over to the k3s (kubernetes) setup. This is something I've been trying to get working for months now and still had no luck; existing tutorials seem to be missing some key new feature or something.

**Comment by chrisbeardy** [comment]
Sorry, I am not familiar with kubernetes so given docker works for me I won't be looking into it.

I recommend using the docker if it's just for personal use, saves the hassle of figuring it out.
