### ISSUE TITLE
mariadb isn´t working

### ISSUE THREAD

**Issue by mateepunkt** [chrisbeardy/nextcloud-docker-raspberrypi-tutorial#9]
First of all I would like to thank you for your super tutorial. very detailed and yet clearly described and easy to understand even for people who do not call english their mother tongue.
one thing I noticed anyway. I use a raspi pi 4 for my nextcloud, and when creating the docker container there was an error message (ERROR: no matching manifest for linux/arm/v7 in the manifest list entries) but this error can be easily solved by simply find another mariadb image that is arm compatible. the images from linuxserver.io (linuxserver/mariadb:latest) are ideal.

**Comment by chrisbeardy** [comment]
Hi, thank you for your comment. I'm glad you found the tutorial useful.

It looks like you downloaded a 32 bit version of Ubuntu or raspberry pi OS. 

The mariadb image in this tutorial only support arm64. But yes good find on the Linux server image. I have used that in the past. 

The tutorial states 64 bit. But I will amend it to make note that if you wish to use a 32 bit OS alternative docker images are available. 

Thanks

**Comment by chrisbeardy** [comment]
updated tutorial with comment about alternative images required for 32 bit
